### ISSUE TITLE
doesn't use MVC file structure

### ISSUE THREAD

**Issue by ipc103** [learn-co-curriculum/super-sinatra-forms#11]
By this point, students have already built out Sinatra using an `app` directory with separate directories for `models`, `views`, and `controllers`, similar to the [basic forms lab](https://github.com/learn-co-curriculum/sinatra-basic-forms). Students were confused as to why the controller was in the root of the directory. 

If we want to reinforce MVC more, it would be better if all of the Sinatra labs used the MVC pattern.

**Comment by jmburges** [comment]
agreed! MVC this guy
